version: "3.8"

services:
  cpp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dice-chess-server
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "make && ./build/main"
